### ISSUE TITLE
Website should be served on GitHub pages.

### ISSUE THREAD

**Issue by JosephBushagour** [ShvetankPrakash/TinyMLWorkshop#1]
Given that this site is being developed on GitHub, it should, at least for testing purposes, be served on [GitHub Pages](https://pages.github.com/). As of now, you need to spin up a local dev instance of this repository in order to view the website which is less than ideal and will eventually need to change. GitHub pages has a lot of benefits, chiefly it's free and ridiculously easy to set up.

**Comment by ShvetankPrakash** [comment]
I completed this issue. See https://shvetankprakash.github.io/TinyMLWorkshop/
However for testing, simply building your code using `bundle exec jekyll serve` and spinning up a local server this way is easier and better to do before pushing your changes to the repo.

**Comment by JosephBushagour** [comment]
Will do, thanks for this!
